### ISSUE TITLE
Issue With Site

### ISSUE THREAD

**Issue by F4dedTV** [TheOriginalAce/DoopChat-For-Facebook#1]
Um Hello, My Website Isnt Working, It Keeps Saying Error 404 Everytime I Try To Start It Up. Is This Something Thats Normal? If Its Not, Please Help Me Out, I Really Wanna Get A Site But I Cant, Please Help, Im Begging You.

**Comment by TheOriginalAce** [comment]
Im Sorry To Hear That, Our Team Is Working To Fix The Site So Please, Be Patient

**Comment by TheOriginalAce** [comment]
Well, Try Again Now, We Just Rebooted The Website

**Comment by F4dedTV** [comment]
Yep it works, thank you so much, have a nice day :)

**Comment by TheOriginalAce** [comment]
Glad To Help, Ask Anytime You Need It

**Comment by TheOriginalAce** [comment]
Wow I Love How You Lied To Me

**Comment by TheOriginalAce** [comment]
Now Im Gonna Report And Remove You From This Repo
